-- REMOVE TODAS AS TABELAS E FUNÇÕES DO BANCO, NA ORDEM INVERSA DA CRIAÇÃO
-- O CASCADE DERRUBA AS CHAVES ESTRANGEIRAS E OS TRIGGERS DEPENDENTES

-- 09 HISTÓRICO
DROP TABLE IF EXISTS
    HISTORICO_PLANO_ALIMENTAR,
    HISTORICO_PLANO_TREINO
CASCADE;

-- 08 FINANCEIRO
DROP TABLE IF EXISTS
    OBSERVACAO_PAGAMENTO,
    PAGAMENTO,
    OBSERVACAO_CONTRATO,
    CONTRATA_PLANO,
    SERVICO_PLANO_SERVICO
CASCADE;

-- 07 EVOLUÇÃO
DROP TABLE IF EXISTS
    META_ALCANCADA_EVOLUCAO,
    OBSERVACAO_EVOLUCAO,
    EVOLUCAO_NUTRICIONAL,
    EVOLUCAO_FISICA
CASCADE;

-- 06 NUTRIÇÃO
DROP TABLE IF EXISTS
    OBSERVACAO_REFEICAO_CONTEM,
    REFEICAO_CONTEM_ALIMENTO,
    REFEICAO,
    OBSERVACAO_PLANO_ALIMENTAR,
    PLANO_ALIMENTAR
CASCADE;

-- 05 TREINO
DROP TABLE IF EXISTS
    OBSERVACAO_TECNICA,
    PLANO_TREINO_PODE_CONTER_EXERCICIO,
    OBSERVACAO_GERAL_PLANO_TREINO,
    OBJETIVO_TREINO,
    PLANO_TREINO
CASCADE;

-- 04 CONSULTAS
DROP TABLE IF EXISTS
    RECOMENDACAO_NUTRICIONAL,
    OBSERVACAO_CLINICA,
    HABITO_ALIMENTAR,
    INTOLERANCIA_CONSULTA_NUTRI,
    OBSERVACAO_GERAL_CONSULTA_FISICA,
    RECOMENDACAO_FISICA,
    OBJETIVO_FISICO_PACIENTE,
    CONSULTA_NUTRICIONAL,
    CONSULTA_FISICA
CASCADE;

-- 03 PROFISSIONAIS
DROP TABLE IF EXISTS
    ESPECIALIDADE_EDUCADOR,
    ESPECIALIDADE_NUTRICIONISTA,
    EDUCADOR_FISICO,
    NUTRICIONISTA,
    TELEFONE_PROFISSIONAL,
    DISPONIBILIDADE_PROFISSIONAL
CASCADE;

-- 02 PACIENTE
DROP TABLE IF EXISTS
    MEDICAMENTO,
    PACIENTE_ALERGIA,
    PACIENTE_DOENCA,
    RESTRICAO_ALIMENTAR,
    RESTRICAO_FISICA,
    CONTATO_EMERGENCIA,
    TELEFONE_PACIENTE
CASCADE;

-- 01 BASE
DROP TABLE IF EXISTS
    EVOLUCAO,
    ALIMENTO,
    EXERCICIO,
    PLANO_SERVICO,
    PROFISSIONAL,
    PACIENTE
CASCADE;

-- FUNÇÕES DOS TRIGGERS
-- O DROP TABLE REMOVE OS TRIGGERS, MAS NÃO AS FUNÇÕES QUE ELES EXECUTAM
DROP FUNCTION IF EXISTS fn_bloquear_imc_manual();
DROP FUNCTION IF EXISTS fn_recalcular_imc_por_altura();
DROP FUNCTION IF EXISTS fn_recalcular_imc_apos_vinculo();
DROP FUNCTION IF EXISTS fn_calcular_imc();
DROP FUNCTION IF EXISTS fn_obter_altura_evolucao(INTEGER);

DROP FUNCTION IF EXISTS fn_bloquear_valor_liquido_manual();
DROP FUNCTION IF EXISTS fn_calcular_valor_liquido();
DROP FUNCTION IF EXISTS fn_obter_valor_mensal_contrato(INTEGER);
